### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by clubdesarrolladores** [matthiasnoback/doctrine-orm-value-object#1]
```
    /**
     * @ValueObject(class="Acme\DemoBundle\Value\PhoneNumber")
     */
    private $phoneNumber;

    private $phoneNumber_number;

    private $phoneNumber_since;
```

We need declare phoneNumber_number and phoneNumber_since? must have that names? Thanks.

**Comment by matthiasnoback** [comment]
Well, I haven't worked on this for a while and I guess you shouldn't use it because Doctrine has now native support for value objects ("embedded objects"). But: those extra fields are necessary because I later add metadata for those properties in order for the data to be stored in columns.

**Comment by clubdesarrolladores** [comment]
I understand. Thanks
